[package]
name = "aerolineas"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
eframe = "=0.29.1"
rand = "0.8.5"
walkers = "=0.25.0"

# incluidas sólo porque sino no compila
winapi = { version = "=0.3.9", features = ["winuser"] }
