[package]
name = "aerolineas"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
eframe = "=0.29.1"
egui_extras = { version = "0.29.1", features = ["all_loaders"] }
image = { version = "0.25.4", features = ["jpeg", "png"] }
rand = "0.8.5"
walkers = "=0.25.0"
