name: aerolineas_rusticas

include:
  - ./docker/compose/networks.yaml
  - ./docker/compose/nodo_10.yaml
  - ./docker/compose/nodo_11.yaml
  - ./docker/compose/nodo_12.yaml
  - ./docker/compose/nodo_13.yaml
  - ./docker/compose/nodo_14.yaml


