[package]
name = "parser"
version = "0.5.0"
authors.workspace = true
edition.workspace = true

[dependencies]
protocol = { path = "../protocol"}
serde = { version = "1.0", features = ["derive"] }
tokenizer = { path = "../tokenizer" }