name: ci

on:
  push:
    branches: [ "main", "feat/**" , "fix/**", "docs/**", "style/**", "refactor/**", "test/**", "chore/**"]
  pull_request:
    branches: [ "main", "feat/**" , "fix/**", "docs/**", "style/**", "refactor/**", "test/**", "chore/**" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  ci:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Run clippy
      run: cargo clippy --all-targets --all-features
